#!/bin/sh

# builtin default config
# sysresources=/etc/X11/xinit/.Xresources
# sysmodmap=/etc/X11/xinit/.Xmodmap
# [ -f "$userresources" ] && xrdb -merge "$userresources"
# [ -f "$usermodmap" ] && xmodmap "$usermodmap"
# merge in defaults and keymaps
[ -f $sysresources ] && xrdb -load ${XDG_CONFIG_HOME-$HOME/.config/X11}/Xresources
# start some nice programs
[ -d /etc/X11/xinit/xinitrc.d ] && for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
	[ -x "$f" ] && . "$f"
done
unset f

# custom config
# basic stuff
xset r rate 200 200
xset m 4 0
setxkbmap -option "ctrl:nocaps"
xmodmap -e "keycode 108 = Super_L"  # reassign Alt_R to Super_L
xmodmap -e "remove mod1 = Super_L"  # make sure X keeps it out of the mod1 group
xsetroot -cursor_name coffee_mug

# startup programs
#type unclutter>/dev/null && unclutter -idle 1 -root -jitter 40
#artha &
dunst &
feh --no-fehbg --bg-scale "$HOME/pix/ddwstdk-7fba4c5a-6ba8-47c0-a5c6-ba0cc2cd0e75.jpg"
picom -f &
bar.sh &
exec dwm

