#!/bin/sh
repos='
/home/vedant36/Documents/textfiles/
/home/vedant36/Documents/CPlus/
/home/vedant36/Documents/Python/
/home/vedant36/Documents/Vedant36.github.io/
/home/vedant36/Downloads/dotfiles/'

[ ! -z "$1" ] && cd $1 && repos=$(ls -A) && dir="$(pwd)/"
for i in $repos;
do
  [ -d "$dir$i" ] && cd "$dir$i" && echo -n "\033[0;35m$i\033[0m " && git status -sb  2>/dev/null &&  cd ../
done
