#!/usr/bin/env python3
# to convert an xml to json
import json
import xmltodict
import sys
with open(sys.argv[1], "r") as xmlfileObj:
    #converting xml data to dictionary
    data_dict = xmltodict.parse(xmlfileObj.read())
    xmlfileObj.close()
    #creating JSON object using dictionary object  
    jsonObj= json.dumps(data_dict)
   
    #storing json data to json file
    with open(sys.argv[1][:-4]+'.json', "w") as jsonfileObj:
        jsonfileObj.write(jsonObj)
        jsonfileObj.close()
