#!/bin/bash
# builtin default config {{{
userresources="$XDG_CONFIG_HOME"/X11/Xresources
# usermodmap=$XDG_CONFIG_HOME/X11/Xmodmap
[ -f "$userresources" ] && xrdb "$userresources"
# [ -f $usermodmap ] && xmodmap $usermodmap
# start some nice programs
[ -d /etc/X11/xinit/xinitrc.d ] && for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
	[ -x "$f" ] && . "$f"
done
unset f

# X configuration {{{1
# resolution
#cvt 1920 1080 60 # put the modeline from this after `xrandr --newmode` as in the next line
xrandr --newmode "1920x1080_60.00" 173.00 1920 2048 2248 2576 1080 1083 1088 1120 -hsync +vsync
xrandr --addmode Virtual-1 1920x1080_60.00
xrandr --output Virtual-1 --mode 1920x1080_60.00
# keyboard
setxkbmap -option altwin:swap_alt_win
setxkbmap -option ctrl:nocaps
# for another mod key
#clear mod3
#keysym F8 = Hyper_R
xset r rate 200 50 # key delay and repeat
xset m 0 0 # mouse speed
# turn off repeat for return and tab
xset -r 36
# screen deactivate and turn off times
xset s expose
xset s blank
xset s 3600
xset s off
xset dpms 3600 3600 3600
xset -dpms
xset s default

# startup programs {{{1
# X only programs
# TODO: write wrapper to check if the command exists and log them with a prefix
# removes cursor from screen after a set itme
xcape -e 'Control_L=Escape' -t 100
unclutter --timeout 2 --jitter 40 --start-hidden --ignore-scrolling &
feh --no-fehbg --bg-fill ~/pix/wallpaper &
dunst &	 # notification server
#xcompmgr &	# compositor
xss-lock -n 'bright -i -5' -l lock &
# display agnostic programs
pactl set-source-mute @DEFAULT_SOURCE@ 1
[ ! -s "$XDG_LIB_HOME"/mpd/pid ] && mpd
emacsclient -a false -e 't' || (emacs --daemon >"$XDG_LOG_HOME"/emacs.log 2>&1) & disown
pgrep artha || artha &	# offline dictionary
pgrep -x mpdscribble > /dev/null || \
	mpdscribble --conf "$HOME"/.local/lib/private/lastfm.conf &
pgrep -x redshift > /dev/null || redshift -l 23.5:78.5 -m randr &

# window manager {{{1
# its in a loop so i can reload configuration by just killing dwm
# and close X by doing pkill -x Xorg
dwm_bar() {
    while xsetroot -name "$(bar.sh)"; do
        # synchronize dwmblocks with the time
        sleep $((60-$(date +%s)%60)) &
        echo $! > "$XDG_STATE_HOME"/sleep_pid
        wait $!
    done
}
# loop until X dies
while xset q &>/dev/null; do
	dwm_bar &
	ssh-agent dwm >"$XDG_LOG_HOME"/dwm.log 2>&1
done
trap 'pkill "$SSH_AGENT_PID";' EXIT HUP TERM QUIT

