#!/usr/bin/env sh
# builtin default config {{{
userresources="$XDG_CONFIG_HOME"/X11/Xresources
# usermodmap=$XDG_CONFIG_HOME/X11/Xmodmap
[ -f "$userresources" ] && xrdb "$userresources"
# [ -f $usermodmap ] && xmodmap $usermodmap
# start some nice programs
[ -d /etc/X11/xinit/xinitrc.d ] && for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
	[ -x "$f" ] && . "$f"
done
unset f

# X configuration {{{1
# resolution
xrandr --newmode "1920x1080_60.00" 173.00 1920 2048 2248 2576 1080 1083 1088 1120 -hsync +vsync
xrandr --addmode Virtual-1 1920x1080_60.00
xrandr --output Virtual-1 --mode 1920x1080_60.00
# keyboard
setxkbmap -option altwin:swap_alt_win
setxkbmap -option ctrl:nocaps
xcape -e 'Control_L=Escape' -t 100
# for another mod key
#clear mod3
#keysym F8 = Hyper_R
xset r rate 200 200
xset -r 36 # turn off repeat for return key
xset m 4 0 # mouse
xset dpms 720 720 720

# startup programs {{{1
# X only programs
# TODO: write wrapper to check if the command exists and log them with a prefix
# removes cursor from screen after a set itme
unclutter --timeout 2 --jitter 40 --start-hidden --ignore-scrolling &
pgrep artha || artha &	# offline dictionary
feh --no-fehbg --bg-fill ~/pix/current* &
dunst &	 # notification server
xcompmgr &	# compositor
xss-lock -n 'bright -i -5' -l lock &
redshift -l 23.5:78.5 &
# display agnostic programs
pactl set-source-mute @DEFAULT_SOURCE@ 1
[ ! -s "$XDG_LIB_HOME"/mpd/pid ] && mpd
pgrep mpdscribble || \
	mpdscribble --conf "$HOME"/.local/lib/private/lastfm.conf &
# pgrep ssh-agent || eval "$(ssh-agent -s)"

# window manager {{{1
# its in a loop so i can reload configuration by just killing dwm
# and close X by doing pkill -x Xorg
# TODO: write a better clean() function for trap to clean-up startup processes
trap 'kill $bar' SIGKILL
while true; do
	while xsetroot -name "$(bar.sh)"; do
		# synchronize dwmblocks with the time
		sleep $((60-$(date +%s)%60)) &
		echo $! > "$XDG_STATE_HOME"/sleep_pid
		wait $!
	done &
	bar=$!
	env XDG_CURRENT_DESKTOP=dwm ssh-agent dwm >"$XDG_LOG_HOME"/dwm.log || exit
done

