#!/bin/sh

# builtin default config {{{
userresources="$XDG_CONFIG_HOME"/X11/Xresources
# usermodmap=$XDG_CONFIG_HOME/X11/Xmodmap
[ -f "$userresources" ] && xrdb "$userresources"
# [ -f $usermodmap ] && xmodmap $usermodmap
# start some nice programs
[ -d /etc/X11/xinit/xinitrc.d ] && for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
	[ -x "$f" ] && . "$f"
done
unset f

# X configuration {{{1
# resolution
xrandr --newmode "1920x1080_60.00" 173.00 1920 2048 2248 2576 1080 1083 1088 1120 -hsync +vsync
xrandr --addmode Virtual-1 1920x1080_60.00
xrandr --output Virtual-1 --mode 1920x1080_60.00
# keyboard
setxkbmap -option altwin:swap_alt_win
setxkbmap -option ctrl:nocaps
xcape -e 'Control_L=Escape' -t 100
# for another mod key
#clear mod3
#keysym F8 = Hyper_R
xset r rate 200 200
xset -r 36 # turn off repeat for return key
xset m 4 0 # mouse
xset dpms 720 720 720

# startup programs {{{1
type unclutter>/dev/null && unclutter --timeout 2 --jitter 40 --start-hidden --ignore-scrolling &
artha &
pactl set-source-mute @DEFAULT_SOURCE@ 1
feh --no-fehbg --bg-fill "$(xdg-user-dir PICTURES)"/current.*
dunst &
xcompmgr &
xss-lock -n 'bright -i -5' -l lock &
redshift -l 23.5:78.5 &
[ ! -s "$XDG_LIB_HOME"/mpd/pid ] && mpd
pgrep mpdscribble || mpdscribble --conf /home/vn36/.local/lib/private/lastfm.conf &
eval "$(ssh-agent -s)"

# window manager {{{1
while xsetroot -name "$(bar.sh)"; do
    # synchronize dwmblocks with the time
    sleep $((60-$(date +%S))) &
	echo $! > "${XDG_STATE_HOME:-$HOME/.cache}"/sleep_pid
	wait $!
done &

while true; do
	# Log stderror to a file
	env XDG_CURRENT_DESKTOP=dwm dwm >"$HOME"/.local/var/log/dwm.log
	# No error logging
	# dwm >/dev/null 2>&1
done

# misc stuff i dont use now/dont work {{{1
# if [ "${XDG_VTNR}" -eq 1 ]; then
#   betterlockscreen -l blur
# fi
# relaunch DWM if the binary changes, otherwise bail
# csum=""
# new_csum=$(sha1sum $(which dwm))
# while true
# do
# 	if [ "$csum" != "$new_csum" ]
# 	then
# 		csum=$new_csum
# 		dwm &>$HOME/.local/var/log/dwm.log
# 	else
# 		exit 0
# 	fi
# 	new_csum=$(sha1sum $(which dwm))
# 	sleep 0.5
# done

